using System.Collections.Generic;
using System.Text;

namespace KioskOsWizard.Models;

/// <summary>
/// Represents a kiosk-os configuration file (kiosk.conf).
/// Serializes to the key=value format consumed by the kiosk-os config-fetcher.
/// </summary>
public class KioskConfig
{
    public string Homepage { get; set; } = "https://example.com";
    public BrowserMode BrowserMode { get; set; } = BrowserMode.Kiosk;
    public List<string> Whitelist { get; set; } = new();

    public ConnectionType Connection { get; set; } = ConnectionType.Wired;
    public string? WifiSsid { get; set; }
    public string? WifiPassword { get; set; }

    public string? Wallpaper { get; set; }
    public string Timezone { get; set; } = "Europe/Berlin";

    public int SessionIdleMinutes { get; set; }
    public int DpmsIdleMinutes { get; set; }

    public bool BlockRemovableDevices { get; set; } = true;

    public string? RemoteConfigUrl { get; set; }
    public bool AutoInstall { get; set; }

    public string ToConfigFileContent()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# kiosk-os configuration");
        sb.AppendLine("# Generated by kiosk-os Setup Wizard");
        sb.AppendLine();

        sb.AppendLine("# === Network ===");
        sb.AppendLine($"connection={(Connection == ConnectionType.Wifi ? "wifi" : "wired")}");
        sb.AppendLine("dhcp=yes");
        if (Connection == ConnectionType.Wifi)
        {
            if (!string.IsNullOrEmpty(WifiSsid)) sb.AppendLine($"wifi_ssid={WifiSsid}");
            if (!string.IsNullOrEmpty(WifiPassword)) sb.AppendLine($"wifi_password={WifiPassword}");
        }
        sb.AppendLine();

        sb.AppendLine("# === Browser ===");
        sb.AppendLine($"homepage={Homepage}");
        sb.AppendLine($"browser_mode={(BrowserMode == BrowserMode.Fullscreen ? "fullscreen" : "kiosk")}");
        if (Whitelist.Count > 0)
        {
            sb.AppendLine($"whitelist={string.Join("|", Whitelist)}");
        }
        sb.AppendLine();

        sb.AppendLine("# === Display ===");
        if (!string.IsNullOrEmpty(Wallpaper)) sb.AppendLine($"wallpaper={Wallpaper}");
        sb.AppendLine($"timezone={Timezone}");
        sb.AppendLine();

        if (SessionIdleMinutes > 0 || DpmsIdleMinutes > 0)
        {
            sb.AppendLine("# === Power Management ===");
            if (SessionIdleMinutes > 0) sb.AppendLine($"session_idle={SessionIdleMinutes}");
            if (DpmsIdleMinutes > 0) sb.AppendLine($"dpms_idle={DpmsIdleMinutes}");
            sb.AppendLine();
        }

        sb.AppendLine("# === Security ===");
        sb.AppendLine($"removable_devices={(BlockRemovableDevices ? "no" : "yes")}");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(RemoteConfigUrl))
        {
            sb.AppendLine("# === Remote Config ===");
            sb.AppendLine($"kiosk_config={RemoteConfigUrl}");
            sb.AppendLine();
        }

        if (AutoInstall)
        {
            sb.AppendLine("# === Installation ===");
            sb.AppendLine("auto_install=yes");
        }

        return sb.ToString();
    }
}

public enum ConnectionType
{
    Wired,
    Wifi,
}

public enum BrowserMode
{
    Kiosk,
    Fullscreen,
}
