using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace KioskOsWizard.Models;

/// <summary>
/// Represents a kiosk-os configuration file (kiosk.conf).
/// Serializes to the key=value format consumed by the kiosk-os config-fetcher.
/// </summary>
public class KioskConfig
{
    public string Homepage { get; set; } = "https://example.com";
    public BrowserMode BrowserMode { get; set; } = BrowserMode.Kiosk;
    public List<string> Whitelist { get; set; } = new();

    public ConnectionType Connection { get; set; } = ConnectionType.Wired;
    public string? WifiSsid { get; set; }
    public string? WifiPassword { get; set; }

    public string? Wallpaper { get; set; }
    public string Timezone { get; set; } = "Europe/Berlin";

    /// <summary>XKB layout code, one of <see cref="KeyboardLayouts.All"/>.</summary>
    public string KeyboardLayout { get; set; } = "us";

    public int SessionIdleMinutes { get; set; }
    public int DpmsIdleMinutes { get; set; }

    public bool BlockRemovableDevices { get; set; } = true;

    public string? RemoteConfigUrl { get; set; }
    public bool AutoInstall { get; set; }

    /// <summary>
    /// Problems that would make the kiosk silently ignore part of the config.
    /// Empty when the config can be written.
    /// </summary>
    public IReadOnlyList<string> Validate()
    {
        var errors = new List<string>();
        if (!(Homepage.StartsWith("http://") || Homepage.StartsWith("https://")))
            errors.Add("The homepage must start with http:// or https://.");

        if (Connection == ConnectionType.Wifi)
        {
            if (string.IsNullOrWhiteSpace(WifiSsid))
                errors.Add("Enter the WiFi network name.");
            else if (Encoding.UTF8.GetByteCount(WifiSsid) > 32)
                errors.Add("A WiFi network name can be at most 32 bytes long.");

            // wpa_passphrase rejects anything else, and the kiosk would come
            // up without network. Empty means an open network.
            var pw = WifiPassword ?? "";
            if (pw.Length > 0 && (pw.Length < 8 || pw.Length > 63))
                errors.Add("A WPA WiFi password has 8 to 63 characters (leave it empty for an open network).");
        }

        return errors;
    }

    public string ToConfigFileContent()
    {
        var lines = new List<string>
        {
            "# kiosk-os configuration",
            "# Generated by kiosk-os Setup Wizard",
            "",
            "# === Network ===",
            $"connection={(Connection == ConnectionType.Wifi ? "wifi" : "wired")}",
            "dhcp=yes",
        };
        if (Connection == ConnectionType.Wifi)
        {
            if (!string.IsNullOrEmpty(WifiSsid)) lines.Add($"wifi_ssid={Clean(WifiSsid)}");
            if (!string.IsNullOrEmpty(WifiPassword)) lines.Add($"wifi_password={Clean(WifiPassword)}");
        }
        lines.Add("");

        lines.Add("# === Browser ===");
        lines.Add($"homepage={Clean(Homepage)}");
        lines.Add($"browser_mode={(BrowserMode == BrowserMode.Fullscreen ? "fullscreen" : "kiosk")}");
        if (Whitelist.Count > 0)
            lines.Add($"whitelist={string.Join("|", Whitelist.Select(Clean))}");
        lines.Add("");

        lines.Add("# === Display ===");
        if (!string.IsNullOrEmpty(Wallpaper)) lines.Add($"wallpaper={Clean(Wallpaper)}");
        lines.Add($"timezone={Clean(Timezone)}");
        lines.Add($"primary_keyboard_layout={Clean(KeyboardLayout)}");
        lines.Add("");

        if (SessionIdleMinutes > 0 || DpmsIdleMinutes > 0)
        {
            lines.Add("# === Power Management ===");
            if (SessionIdleMinutes > 0) lines.Add($"session_idle={SessionIdleMinutes}");
            if (DpmsIdleMinutes > 0) lines.Add($"dpms_idle={DpmsIdleMinutes}");
            lines.Add("");
        }

        lines.Add("# === Security ===");
        lines.Add($"removable_devices={(BlockRemovableDevices ? "no" : "yes")}");
        lines.Add("");

        if (!string.IsNullOrEmpty(RemoteConfigUrl))
        {
            lines.Add("# === Remote Config ===");
            lines.Add($"kiosk_config={Clean(RemoteConfigUrl)}");
            lines.Add("");
        }

        if (AutoInstall)
        {
            lines.Add("# === Installation ===");
            lines.Add("auto_install=yes");
        }

        // Always LF: the kiosk parses this with shell tools, and the wizard
        // must produce the same file on Windows as on Linux.
        return string.Join("\n", lines) + "\n";
    }

    /// <summary>
    /// One value per line: a line break inside a value would let it inject
    /// further keys (auto_install=yes, kiosk_config=...) into the file.
    /// </summary>
    private static string Clean(string value) =>
        value.Replace("\r", "").Replace("\n", "").Trim();
}

public enum ConnectionType
{
    Wired,
    Wifi,
}

public enum BrowserMode
{
    Kiosk,
    Fullscreen,
}
