# kiosk-os default configuration
# This is loaded when no USB or remote config is found.

homepage=https://github.com/LennartKleymann/kiosk-os
connection=wired
dhcp=yes
timezone=Europe/Berlin
primary_keyboard_layout=de
disable_navigation_bar=yes
